---

- name: Debconf options
  debconf:
    name: postifx
    question: "postfix/{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "string"
  with_items:
    - {question: mailname, value: "{{ mailname }}"}
    - {question: main_mailer_type, value: "'Internet Site'"}
  when:
    - ansible_distribution == 'Debian'

- name: Install
  package:
    name:
      - postfix
      - mailutils
      - libsasl2-modules
    state: present
  when:
    - ansible_distribution == 'Debian'

- name: Install
  package:
    name:
      - postfix
      - mailx
    state: present
  when:
    - ansible_distribution == 'Fedora'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/postfix
    - /etc/postfix/sasl

- name: Configure
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: etc/postfix/main.cf, dest: /etc/postfix/main.cf}
  notify:
    - restart postfix

- name: Aliases
  lineinfile:
    dest: /etc/aliases
    regexp: '^{{ item.key }}'
    line: '{{ item.key }}: {{ item.value }}'
    state: present
  with_dict: "{{ mail_aliases }}"
  register: set_alias
  notify:
    - reload alias
    - restart postfix

- name: Relay settings
  template:
    src: "etc/postfix/sasl/sasl_passwd.j2"
    dest: "/etc/postfix/sasl/sasl_passwd"
    owner: root
    group: root
    mode: '600'
  when: postfix_relay.address
  notify:
    - regenerate relay settings
    - restart postfix

- name: Generic settings
  template:
    src: "etc/postfix/generic.j2"
    dest: "/etc/postfix/generic"
    owner: root
    group: root
    mode: '600'
  when: postfix_generic | length > 0
  notify:
    - regenerate generic settings
    - restart postfix

- name: Enable
  service:
    name: postfix
    state: started
    enabled: yes
